# Generated by Django 4.1.3 on 2022-11-11 10:12

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars_data',
            fields=[
                ('car_Id', models.AutoField(primary_key=True, serialize=False)),
                ('car_Name', models.CharField(max_length=100)),
                ('Car_Model', models.CharField(max_length=100)),
                ('car_Price', models.IntegerField(max_length=15)),
                ('car_Photo', models.FileField(null=True, upload_to=cars.models.user_directory_path, verbose_name='')),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
